### PR TITLE
Closes #14

### LINKED ISSUE #14: Running proofreader shows Exception classes with inconsistent naming
```
$ ../proofreader-php/bin/proofreader src/                                                                                    
PHP-CS-Fixer consistency check with local project
PHP-CS-Fixer
Loaded config from "/home/giorgio/code/proofreader-php/.php_cs.dist"
...................
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
Checked all files in 1.365 seconds, 6.000 MB memory used
PHPMD

/home/giorgio/code/api-sdk-php/src/Exception/ApiException.php:8 Do not suffix exception names with Exception
/home/giorgio/code/api-sdk-php/src/Exception/ApiProblemException.php:10 Do not suffix exception names with Exception
/home/giorgio/code/api-sdk-php/src/Exception/HttpException.php:8        Do not suffix exception names with Exception
/home/giorgio/code/api-sdk-php/src/Exception/NetworkException.php:5     Do not suffix exception names with Exception
/home/giorgio/code/api-sdk-php/src/Exception/ResponseException.php:9    Do not suffix exception names with Exception
PHPCPD
phpcpd 2.0.4 by Sebastian Bergmann.

0.00% duplicated lines out of 649 total lines of code.

Time: 38 ms, Memory: 2.00MB
```

Who's right, this code or the coding standard telling us not to use the `*Exception` suffix?

### PR DESCRIPTION
**Pull request by giorgiosironi**

### CODE REVIEW

File: spec/Exception/ApiProblemResponseSpec.php [hunk 1]
```diff
@@ -53,6 +53,6 @@ public function it_can_have_a_previous_exception(Exception $previous)
 
     public function it_is_a_response_exception()
```
Comment (thewilkybarkid) [inline spec/Exception/ApiProblemResponseSpec.php]: Should rename these.

Comment (thewilkybarkid) [inline spec/Exception/ApiProblemResponseSpec.php]: `it_is_a_bad_response` etc.

File: src/HttpClient/Guzzle6HttpClient.php [hunk 2]
```diff
@@ -4,9 +4,9 @@
 
 use Crell\ApiProblem\ApiProblem;
 use eLife\ApiSdk\Exception\ApiException;
-use eLife\ApiSdk\Exception\ApiProblemException;
-use eLife\ApiSdk\Exception\NetworkException;
-use eLife\ApiSdk\Exception\ResponseException;
+use eLife\ApiSdk\Exception\ApiProblemResponse;
+use eLife\ApiSdk\Exception\NetworkProblem;
+use eLife\ApiSdk\Exception\BadResponse;
```
Comment (thewilkybarkid) [inline src/HttpClient/Guzzle6HttpClient.php]: PHP-CS-Fixer should fix the ordering.

Comment (giorgiosironi) [inline src/HttpClient/Guzzle6HttpClient.php]: With our `.php_cs` it seems that it doesn't:
```
$ ../proofreader-php/vendor/bin/php-cs-fixer --config-file=.php_cs fix src
Loaded config from ".php_cs"
Fixed all files in 1.256 seconds, 6.000 MB memory used
$ git diff
(empty output)
```

Maybe it's because:
`The "contrib level" fixers cannot be enabled via this option; you should instead set them manually by their name via the --fixers option.`
and we only have `-empty_return` in there?

Comment (giorgiosironi) [inline src/HttpClient/Guzzle6HttpClient.php]: Check out the last commit.

Comment (thewilkybarkid) [inline src/HttpClient/Guzzle6HttpClient.php]: Ah, we should enable that everywhere.

Shame about the `use function` though, wonder if that's an upstream bug or intentional.

**Comment by giorgiosironi** [comment]
The `use function` is not implemented yet: https://github.com/phpmd/phpmd/issues/384

**Comment by giorgiosironi** [comment]
As for the everywhere: https://github.com/elifesciences/proofreader-php/pull/2
